### ISSUE TITLE
Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app)."

### ISSUE THREAD

**Issue by vincepunkrock** [Polymer/polycasts#16]
I just watched and followed your polycasts #57 and #58. The integration of firebase-auth went all right but then it broke when I added the <my-notes> element and firebase-query. I could not find the cause so I came here and copied your code but I still get the error. 

`Uncaught Vcode: "app/duplicate-app"message: "Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app)."name: "[DEFAULT]"stack: "FirebaseError: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).↵    at Z (http://localhost:5000/bower_components/firebase/firebase-app.js:27:364)↵    at Object.initializeApp (http://localhost:5000/bower_components/firebase/firebase-app.js:26:29)↵    at HTMLElement.__computeApp (http://localhost:5000/bower_components/polymerfire/firebase-app.html:117:36)↵    at HTMLElement._computeEffect (http://localhost:5000/bower_components/polymer/polymer.html:1684:24)↵    at HTMLElement._effectEffects (http://localhost:5000/bower_components/polymer/polymer.html:1507:7)↵    at HTMLElement._propertySetter (http://localhost:5000/bower_components/polymer/polymer.html:1491:6)↵    at HTMLElement.__setProperty (http://localhost:5000/bower_components/polymer/polymer.html:1500:6)↵    at HTMLElement._applyConfig (http://localhost:5000/bower_components/polymer/polymer.html:2110:6)↵    at HTMLElement._afterClientsReady (http://localhost:5000/bower_components/polymer/polymer.html:2104:6)↵    at HTMLElement._ready (http://localhost:5000/bower_components/polymer/polymer-mini.html:70:6)"__proto__: Error
`

Do you have an idea of how I could fix this?

**Comment by RStyrman** [comment]
hi polyfire/firebase-app.html pulls in polymer/polymer.html so if your importing polymer and polymerfire in one of your files you can get that (had it happend to me :))

**Comment by RStyrman** [comment]
Duplicate imports, might be looping (I had some issues right now with it too, (again)) but it went away after double checking everything. (you also get the error message if you load polymer in the same document as polymerfire

**Comment by RStyrman** [comment]
It gave me that error too when missing importing things, (was doing polycast #58 and forgot to bower install iron-icons and was giving me very vague errors like poster)

**Comment by RStyrman** [comment]
Nevermind, I have no idea, stuck at same thing, around the last steps at the tutorial I broke mine aswell, trouble figuring it out

**Comment by RStyrman** [comment]
trying to figure this out, so far I narrowed it down to notes.html
If I comment out





 I don't get errors

**Comment by tony19** [comment]
@RStyrman I can't reproduce your symptoms (no errors for me using original code from [ep58-firebase-db-demo](https://github.com/Polymer/polycasts/tree/master/ep58-firebase-db-demo)). Can you provide details about your environment and steps to reproduce? Here's my info for comparison:

### Steps
 1. Run the following commands:
 ```shell
git clone https://github.com/Polymer/polycasts.git
cd polycasts/ep58-firebase-db-demo
bower i
firebase serve
```
 2. Open Chrome 56 to http://localhost:5000, and verify it looks similar to this screenshot (I've added a note here `this is a test`):

 ![screen shot 2017-02-27 at 7 38 26 pm](https://cloud.githubusercontent.com/assets/26580/23387819/80d4e1aa-fd24-11e6-883f-8f19e5499cf8.png)

 3. Open console in DevTools, and verify there are no warnings/errors.

### Environment
 * macOS Sierra 10.12
 * node 7.6.0
 * `firebase-tools` 3.4.0

**Comment by RStyrman** [comment]
works for me now too.. (this is confusing, I got another copy of the repo pulled the 1-2 days ago and that one is failing)

**Comment by RStyrman** [comment]
something is up, so I got the error again, firebase serve second time (I did get it to work on first try)

**Comment by RStyrman** [comment]
**Environment:**
Ubuntu 16,04
Node: v7.5.0
Firebase tools: 3.4.0
Google Chrome 56.0.2924.87 

Clues:
Something in my browser messing it up, It worked in incognito... >_>

**Comment by RStyrman** [comment]
I really don't know what's going on, I tried disabling all my extensions and I refresh the cache by using ctrl + f5, it works in incognito and not in non incognito

**Comment by tony19** [comment]
Does <kbd>CTRL</kbd>+<kbd>F5</kbd> actually clear the cache before reloading in Windows? Try opening DevTools, then right-click the refresh button, and choose "Empty cache and hard reload". http://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome

**Comment by RStyrman** [comment]
your right, it didn't me :snail:

**Comment by jbsheds** [comment]
I was having the exact same problem. Following RStyrman, I removed some of the imports which helped me figure out that the error was that I didn't have paper-input installed in the bower_components directory. It makes no sense to me why that gave me a "firebase app already exists" error, but installing paper-input (bower install --save PolymerElements/paper-input) fixed the error.

The demo is all working now. I'm sure that exact thing isn't everyone's problem, but I guess the bigger lesson is that error does not necessarily have anything to do with firebase.

**Comment by bobtista** [comment]
This happens if you leave out or misspell an import. It also seems to happen if the name starts with "main" as in "main-page"  or "main-view" for polymer elements. Not sure why, but I was able to take the exact same file, and rename it to "view-main" and it started working.

**Comment by AnsarSamad** [comment]
the issue is due to calling the initialize method of firebase more than multiple times . me had this same issue . and i could fix it by restricting the initialize method call more than once . make the firebase configurations in one class and make it as singleton class .

**Comment by Mikebarson** [comment]
I had a similar error. My imports were:


    <script src="/__/firebase/4.0.0/firebase-app.js"></script>
    <script src="/__/firebase/4.0.0/firebase-auth.js"></script>
    <script src="/__/firebase/4.0.0/firebase-database.js"></script>
    <script src="/__/firebase/4.0.0/firebase-messaging.js"></script>
    <script src="/__/firebase/init.js"></script>

    
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js"></script>

    
    <script src="https://www.gstatic.com/firebasejs/3.6.6/firebase.js"></script>

    
    <script src="https://cdn.firebase.com/libs/angularfire/2.3.0/angularfire.min.js"></script>

    
    <script src="app.js"></script>

I changed the firebase.js cdn to 4.0.0 and it fixed the "Firebase app [DEFAULT] already exists"  error.

**Comment by crawftv** [comment]
Right-clicking on the browser's refresh icon and selecting "hard refresh and clear cache" is what solved my problem with this error. Try running your app on incognito or using the refresh before jumping to some of the conclusions on here. I spent at least forty minutes going through every file before doing the refresh.

**Comment by DedoJr** [comment]
On firebase web, you check if already initialized with:

if (!firebase.apps.length) {
    firebase.initializeApp({});
}
